export const productData = [
    {
        id: 1,
        valor: 50.00,
        nome: "Bolsa de Malha Artesanal Pequena",        
        data_publicacao: "2024-02-01",                        
        descricao: "Esta encantadora bolsa artesanal é perfeita para quem busca estilo e originaidde. Feita à mão com malha artesanal de alta quaidde, cada bolsa é única e reflete o trabalho artístico de seu artesão. Além de ser uma escolha elegante, esta bolsa é uma declaração de apoio ao artesanato tradicional.",        
        quantidade: 1,
        total: 50.00,
        details: {
            resume: "Bolsa Artesanal Pequena",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805506/dabru-atelie/dabruatelie_1706805507087_vat7gx.jpg",
            sobre: "Uma bolsa pequena feita à mão com malha artesanal.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Artesanal",
            delivery: true,
            dimX: 20,
            dimY: 10,            
        }
    },
    {
        id: 2,
        valor: 70.00,
        nome: "Bolsa de Malha Feita à Mão Média",
        data_publicacao: "2024-02-01",
        descricao: "Esta deslumbrante bolsa média é uma peça única que combina estilo e artesanato. Feita à mão com malha de alta quaidde, cada detalhe é ciddosamente trabalhado para garantir durabiidde e elegância. Perfeita para quem busca uma bolsa que seja tão funcional quanto bonita.",
        quantidade: 1,
        total: 70.00,
        details: {
            resume: "Bolsa Feita à Mão Média",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805509/dabru-atelie/dabruatelie_1706805503217_e8xc98.jpg",
            sobre: "Uma bolsa média feita à mão com malha de alta quaidde.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Feita à Mão",
            delivery: true,
            dimX: 25,
            dimY: 15,
        }        
    },
    {
        id: 3,
        valor: 60.00,
        nome: "Bolsa de Malha Ecológica",
        data_publicacao: "2024-02-01",
        descricao: "Esta bolsa ecológica é mais do que apenas uma peça de moda; é um símbolo de compromisso com a sustentabiidde. Feita com malha sustentável de alta quaidde, esta bolsa é uma escolha consciente para quem se preocupa com o meio ambiente. Além disso, seu design elegante e versátil a torna perfeita para qualquer ocasião.",
        quantidade: 1,
        total: 60.00,
        details: {
            resume: "Bolsa Ecológica",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805504/dabru-atelie/dabruatelie_1706805520066_vup0lu.jpg",
            sobre: "Uma bolsa ecológica feita com malha sustentável.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Ecológica",
            delivery: true,
            dimX: 30,
            dimY: 20,
        }        
    },
    {
        id: 4,
        valor: 55.00,
        nome: "Bolsa de Malha Coloid",
        data_publicacao: "2024-02-01",
        descricao: "Esta vibrante bolsa coloid é uma explosão de alegria e estilo. Com seu design único e malha de alta quaidde, ela é perfeita para adicionar um toque de cor e vivaidde ao seu visual. Seja para um passeio descontraído ou uma saída à noite, esta bolsa certamente chamará a atenção.",
        quantidade: 1,
        total: 55.00,
        details: {
            resume: "Bolsa Coloid",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805503/dabru-atelie/dabruatelie_1706805517927_f7hspm.jpg",
            sobre: "Uma bolsa coloid com design único feita de malha.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Coloid",
            delivery: true,
            dimX: 25,
            dimY: 15,
        }        
    },
    {
        id: 5,
        nome: "Bolsa de Malha Artesanal Grande",
        valor: 80.00,
        data_publicacao: "2024-02-01",
        descricao: "Esta deslumbrante bolsa artesanal grande é uma verdadeira declaração de estilo. Com seus detalhes artesanais e malha de alta quaidde, ela é espaçosa o suficiente para acomodar todos os seus itens essenciais com elegância. Seja para o trabalho ou lazer, esta bolsa irá impressionar.",
        quantidade: 1,
        total: 80.00,
        details: {
            resume: "Bolsa Artesanal Grande",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805502/dabru-atelie/dabruatelie_1706805526313_gumknv.jpg",
            sobre: "Uma bolsa grande com detalhes artesanais em malha.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Artesanal",
            delivery: true,
            dimX: 30,
            dimY: 20,
        }        
    },
    {
        id: 6,
        nome: "Bolsa de Malha Feita à Mão Pequena",
        valor: 45.00,
        data_publicacao: "2024-02-01",
        descricao: "Esta encantadora bolsa pequena é uma peça única que combina estilo e artesanato. Feita à mão com malha de alta quaidde, cada detalhe é ciddosamente trabalhado para garantir durabiidde e elegância. Perfeita para quem busca uma bolsa que seja tão funcional quanto bonita.",
        quantidade: 1,
        total: 45.00,
        details: {
            resume: "Bolsa Feita à Mão Pequena",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805500/dabru-atelie/dabruatelie_1706805475976_r0s43d.jpg",
            sobre: "Uma bolsa pequena feita à mão com malha de quaidde.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Feita à Mão",
            delivery: false,
            dimX: 20,
            dimY: 10,
        }

    },
    {
        id: 7,
        nome: "Bolsa de Malha Vintage",
        valor: 65.00,
        data_publicacao: "2024-02-01",
        descricao: "Esta bolsa vintage é uma peça atemporal que combina estilo e elegância. Com seu design clássico e malha de alta quaidde, ela é perfeita para quem busca um toque de sofisticação. Seja para um evento formal ou casual, esta bolsa certamente fará uma declaração de estilo.",
        quantidade: 1,
        total: 65.00,
        details: {
            resume: "Bolsa Vintage",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805499/dabru-atelie/dabruatelie_1706805465281_hkkezi.jpg",
            sobre: "Uma bolsa vintage com estilo clássico em malha.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Vintage",
            delivery: true,
            dimX: 25,
            dimY: 15,
        }
    },
    {
        id: 8,
        nome: "Bolsa de Malha com Detalhes em Couro",
        valor: 75.00,
        data_publicacao: "2024-02-01",
        descricao: "Esta elegante bolsa combina o melhor do estilo e da funcionaidde. Com detalhes em couro e malha de alta quaidde, ela é perfeita para quem busca uma bolsa que seja tão elegante quanto prática. Seja para o trabalho ou lazer, esta bolsa irá impressionar.",
        quantidade: 1,
        total: 75.00,
        details: {
            resume: "Bolsa com Detalhes em Couro",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805498/dabru-atelie/dabruatelie_1706805327304_rwcira.jpg",
            sobre: "Uma bolsa elegante com detalhes em couro e malha.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Couro",
            delivery: false,
            dimX: 30,
            dimY: 20,
        }       
    },
    {
        id: 9,
        nome: "Bolsa de Malha Boho Chic",
        valor: 85.00,
        data_publicacao: "2024-02-01",
        descricao: "Esta bolsa boho chic é uma peça única que combina estilo e originaidde. Com malha de alta quaidde e um design elegante, ela é perfeita para quem busca uma bolsa que seja tão funcional quanto bonita. Seja para um passeio descontraído ou uma saída à noite, esta bolsa certamente chamará a atenção.",
        quantidade: 1,
        total: 85.00,
        details: {
            resume: "Bolsa Boho Chic",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805498/dabru-atelie/dabruatelie_1706805495770_peb4eo.jpg",
            sobre: "Uma bolsa com estilo boho chic em malha de alta quaidde.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Boho Chic",
            delivery: false,
            dimX: 30,
            dimY: 20,
        }        
    },
    {
        id: 10,
        nome: "Bolsa de Malha Retrô",
        valor: 60.00,
        descricao: "Esta bolsa retrô é uma peça atemporal que combina estilo e elegância. Com seu design clássico e malha de alta quaidde, ela é perfeita para quem busca um toque de sofisticação. Seja para um evento formal ou casual, esta bolsa certamente fará uma declaração de estilo.",
        data_publicacao: "2024-02-01",
        quantidade: 1,
        total: 60.00,
        details: {
            resume: "Bolsa Retrô",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805501/dabru-atelie/dabruatelie_1706805490172_eqwhgl.jpg",
            sobre: "Uma bolsa com design retrô feita de malha.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Retrô",
            delivery: true,
            dimX: 25,
            dimY: 15,
        }        
    },
    {
        id: 11,
        nome: "Bolsa de Malha Ecológica",
        valor: 60.00,
        data_publicacao: "2024-02-01",
        descricao: "Esta bolsa ecológica é mais do que apenas uma peça de moda; é um símbolo de compromisso com a sustentabiidde. Feita com malha sustentável de alta quaidde, esta bolsa é uma escolha consciente para quem se preocupa com o meio ambiente. Além disso, seu design elegante e versátil a torna perfeita para qualquer ocasião.",
        quantidade: 1,
        total: 60.00,
        details: {
            resume: "Bolsa Ecológica",
            imgLink: "https://res.cloudinary.com/dh39ahmpj/image/upload/v1706805504/dabru-atelie/dabruatelie_1706805520066_vup0lu.jpg",
            sobre: "Uma bolsa ecológica feita com malha sustentável.",
            observacao: "As cores e padrões podem variar deid à natureza artesanal deste produto.",
            tipo: "Ecológica",
            delivery: false,
            dimX: 30,
            dimY: 20,
        }
    },
];